services:
  backend-dev:
    build:
      context: ./backend
      target: development
    restart: always
    ports:
      - ${PORT_BACKEND}:6677
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
  db:
    image: mysql:8.4.6-oraclelinux9
    restart: always
    ports:
      - ${PORT_DB}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
      - db-conf:/etc/mysql/conf.d
  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    restart: always
    ports:
      - ${PORT_PHPMYADMIN}:80
    environment:
      - PMA_HOST=db
volumes:
  db-data:
  db-conf: