services:
  backend-dev:
    container_name: backend-dev
    build:
      context: ./backend
      target: development
    restart: always
    ports:
      - ${PORT_BACKEND}:6677
    environment:
      - PORT=6677
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    depends_on:
      db:
        condition: service_healthy
  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      target: development
    restart: always
    ports:
      - ${PORT_FRONTEND}:3000
    volumes:
      - ./frontend:/app
    env_file: ./frontend/.env
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql:8.4.6-oraclelinux9
    restart: always
    ports:
      - ${PORT_DB}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
      - db-conf:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  phpmyadmin:
    image: phpmyadmin:5.2.2
    depends_on:
      - db
    restart: always
    ports:
      - ${PORT_PHPMYADMIN}:80
    environment:
      - PMA_HOST=db
volumes:
  db-data:
  db-conf: